version: '3.7'
services:
  cade_db:
    image: postgres
    restart: always
    container_name: cade_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '23332:5432'
    volumes:
      - ./docker_db:/var/lib/postgresql/data