version: '3.7'
services:
  cade_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '23332:5432'
    volumes:
      - ./docker_db:/var/lib/postgresql/data
  cade_api:
    build: .
    ports:
      - 23274:23274
    volumes:
      - ./src/:/app/
    entrypoint: "npm run local"
    environment:
      DB_PORT: '23332'
      DB_HOST: cade_db
      DB_PW: postgres
      DB_USER: postgres
      DB_NAME: whims_cade_db